Feature/trip duration
miriam-ertl/my-trips pull request #28
Opened 2023-10-10 11:07 UTC by DaveKrauss

2023-10-10 12:58 UTC, ahohnsen approved these changes
Good job 🙌🏼

2023-10-11 08:07 UTC, JessicaLoers requested changes
**Well Done Team 🐸**
Please see my comments and the points we discussed in the Daily this morning.

2023-10-11 08:07 UTC, JessicaLoers commented on components/Trip/index.js
>          <StyledImage src={image} width={70} height={70} alt="" />
This is not part of the PR, but I suggest to use a more meaningful alt description for the image to aid with accessibility.

```suggestion
        <StyledImage src={image} width={70} height={70} alt={`Image for trip titled ${title}`} />
```

2023-10-11 08:07 UTC, JessicaLoers commented on pages/trips/[id]/index.js
> +  );
Please see my previous comments regarding `DisplayCountdown()` function the and the points we discussed in the Daily. 💚

2023-10-11 10:27 UTC, JessicaLoers approved these changes
**Well done ✨**

2023-10-11 12:04 UTC, merged